export enum SocketEventEnum {
    UNKNOWN = "UNKNOWN",
    CLIENT_REQUEST_MESSAGES = "CLIENT_REQUEST_MESSAGES",
    SERVER_RESPOND_MESSAGES = "SERVER_RESPOND_MESSAGES",
    TEXT_MESSAGE = "TEXT_MESSAGE",
    LOGIN = "LOGIN",
    LOGIN_USERNAME_TAKEN ="LOGIN_USERNAME_TAKEN",
    LOGIN_USERNAME_ACCEPT ="LOGIN_USERNAME_ACCEPT",
    LOGOUT = "LOGOUT",
    SYSTEM_INFO = "SYSTEM_INFO",
    SYSTEM_WARNING = "SYSTEM_WARNING",
    SYSTEM_ERROR = "SYSTEM_ERROR",
}
