export enum ClientEvent {
    REQUEST_LOGIN = "C_REQUEST_LOGIN",

    REQUEST_MESSAGE_LIST = "C_REQUEST_MESSAGE_LIST",
    REQUEST_ONLINE_USERS = "C_REQUEST_ONLINE_USERS",
    
    REQUEST_CHATROOM_EXISTS = "C_REQUEST_CHATROOM_EXISTS",
    REQUEST_CREATE_CHATROOM = "C_REQUEST_CREATE_CHATROOM",
    REQUEST_JOIN_CHATROOM = "C_REQUEST_JOIN_CHATROOM",
    REQUEST_LEAVE_CHATROOM = "C_REQUEST_LEAVE_CHATROOM",

    SEND_TEXT_MESSAGE = "C_SEND_TEXT_MESSAGE", 
}
