export enum MessageType {
    // PRIMITIVES
    BOOLEAN = "BOOLEAN",
    NUMBER = "NUMBER",
    STRING = "STRING",

    // ALIASES
    USERNAME = "USERNAME",
    CHATROOM = "CHATROOM",

    // INTERFACES
    TEXT = "TEXT",
    SYSTEM = "SYSTEM",
    MESSAGE_LIST = "MESSAGE_LIST",
    USERNAME_LIST = "USERNAME_LIST",
}
