export enum ServerEvent {
    RESPONSE_MESSAGE_LIST = "S_RESPONSE_MESSAGE_LIST",
    RESPONSE_ONLINE_USERS = "S_RESPONSE_ONLINE_USERS",
    
    SEND_TEXT_MESSAGE = "S_SEND_TEXT_MESSAGE",
    SEND_SYSTEM = "S_SEND_SYSTEM",

    RESPONSE_LOGIN_USERNAME_ACCEPT = "S_RESPONSE_LOGIN_USERNAME_ACCEPT",
    RESPONSE_LOGIN_USERNAME_TAKEN = "S_RESPONSE_LOGIN_USERNAME_TAKEN",

    SEND_JOIN_CHATROOM = "S_SEND_JOIN_CHATROOM",
    SEND_LEAVE_CHATROOM = "S_SEND_LEAVE_CHATROOM",
    RESPONSE_CHATROOM_EXISTS = "S_RESPONSE_CHATROOM_EXISTS",
    RESPONSE_CHATROOM_NOT_EXISTS = "S_RESPONSE_CHATROOM_NOT_EXISTS",
    RESPONSE_CHATROOM_LIMIT_REACHED = "S_RESPONSE_CHATROOM_LIMIT_REACHED",
    RESPONSE_CREATE_CHATROOM_ACCEPT = "S_RESPONSE_CREATE_CHATROOM_ACCEPT",
    RESPONSE_CREATE_CHATROOM_TAKEN = "S_RESPONSE_CREATE_CHATROOM_TAKEN",    
    RESPONSE_JOIN_CHATROOM_ACCEPT = "S_RESPONSE_JOIN_CHATROOM_ACCEPT",
    RESPONSE_JOIN_CHATROOM_NOT_EXISTING = "S_RESPONSE_JOIN_CHATROOM_NOT_EXISTING",    
    RESPONSE_LEAVE_CHATROOM_ACCEPT = "S_RESPONSE_JOIN_CHATROOM_ACCEPT",
    RESPONSE_LEAVE_CHATROOM_NOT_JOINED = "S_RESPONSE_LEAVE_CHATROOM_NOT_JOINED",
}
