export enum MessageType {
    LOGIN = "LOGIN",
    LOGOUT = "LOGOUT",
    SYSTEM_ERROR = "SYSTEM_ERROR",
    SYSTEM_INFO = "SYSTEM_INFO",
    SYSTEM_WARNING = "SYSTEM_WARNING",
    MESSAGE_LIST_LIMIT = "MESSAGE_LIST_LIMIT",
    MESSAGE_LIST = "MESSAGE_LIST",
    TEXT = "TEXT",
    USERNAME_TAKEN = "USERNAME_TAKEN",
    USERNAME_ACCEPT = "USERNAME_ACCEPT",
}
