export enum SocketEvent {
    CLIENT_REQUESTS_MESSAGE_LIST = "CLIENT_REQUESTS_MESSAGES",
    CLIENT_SENDS_TEXT_MESSAGE = "CLIENT_SENDS_TEXT_MESSAGE",
    SERVER_SENDS_TEXT_MESSAGE = "SERVER_SENDS_TEXT_MESSAGE",
    CLIENT_REQUESTS_LOGIN = "CLIENT_REQUESTS_LOGIN",
    SERVER_RESPONDS_LOGIN_USERNAME_TAKEN = "SERVER_RESPONDS_LOGIN_USERNAME_TAKEN",
    SERVER_RESPONDS_LOGIN_USERNAME_ACCEPT = "SERVER_RESPONDS_LOGIN_USERNAME_ACCEPT",
    SERVER_SENDS_LOGIN = "SERVER_SENDS_LOGIN",
    SERVER_SENDS_LOGOUT = "SERVER_SENDS_LOGOUT",
    SERVER_SENDS_SYSTEM_INFO = "SERVER_SENDS_SYSTEM_INFO",
    SERVER_SENDS_SYSTEM_WARNING = "SERVER_SENDS_SYSTEM_WARNING",
    SERVER_SENDS_SYSTEM_ERROR = "SERVER_SENDS_SYSTEM_ERROR",
}
